name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test_ubuntu_latest:
    name: Compile and run Tests
    
    runs-on: ubuntu-latest
    
    container:
      image: gnuoctave/octave:latest
      volumes:
        - ${{ github.workspace }}:/app

    steps:
      - name: Check Out the Repo
        uses: actions/checkout@v4
        with:
          submodules: 'false'

      - name: Build oct-hdf5
        run: make -j $(nproc)

      - name: Test oct-hdf5
        run: make check

  build_and_test_ubuntu_20_04:
    name: Compile and run Tests
    
    runs-on: ubuntu-20.04

    steps:
      - name: Check Out the Repo
        uses: actions/checkout@v4
        with:
          submodules: 'false'
          
      - name: Install Stock Octave
        timeout-minutes: 5
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install octave-dev

      - name: Build oct-hdf5
        run: make -j $(nproc)

      - name: Test oct-hdf5
        run: make check

  build_and_test_ubuntu_22_04:
    name: Compile and run Tests
    
    runs-on: ubuntu-22.04

    steps:
      - name: Check Out the Repo
        uses: actions/checkout@v4
        with:
          submodules: 'false'
          
      - name: Install Stock Octave
        timeout-minutes: 5
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install octave-dev

      - name: Build oct-hdf5
        run: make -j $(nproc)

      - name: Test oct-hdf5
        run: make check
