name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test_ubuntu_latest:
    name: Compile and run Tests Ubuntu Latest
    
    runs-on: ubuntu-latest
    
    container:
      image: gnuoctave/octave:latest
      volumes:
        - ${{ github.workspace }}:/app

    steps:
      - name: Check Out the Repo
        uses: actions/checkout@v4
        with:
          submodules: 'false'

      - name: Build oct-hdf5
        run: make -j $(nproc)

      - name: Test oct-hdf5
        run: make check
        
  build_and_test_mac_latest:
    name: Compile and run Tests Mac Latest
    
    runs-on: macos-latest

    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        
      - name: Install Octave
        id: install-octave
        uses: gerlero/brew-install@v1
        with:
          packages: octave
        
      - name: Install Gnu grep
        id: install-octave
        uses: gerlero/brew-install@v1
        with:
          packages: grep
          
      - name: Check Out the Repo
        uses: actions/checkout@v4
        with:
          submodules: 'false'

      - name: Build oct-hdf5
        run: make -j $(nproc)

      - name: Test oct-hdf5
        run: make check
        
      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: test/fntests.log
