name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test_ubuntu_latest:
    name: Compile and run Tests Latest
    
    runs-on: ubuntu-latest
    
    container:
      image: gnuoctave/octave:latest
      volumes:
        - ${{ github.workspace }}:/app

    steps:
      - name: Check Out the Repo
        uses: actions/checkout@v4
        with:
          submodules: 'false'

      - name: Build oct-hdf5
        run: make -j $(nproc)

      - name: Test oct-hdf5
        run: make check

  build_and_test_ubuntu_20.04_5.2:
    name: Compile and run Tests 20.04/5.2
    
    runs-on: ubuntu-20.04
    
    container:
      image: gnuoctave/octave:5.2.0
      volumes:
        - ${{ github.workspace }}:/app

    steps:
      - name: Check Out the Repo
        uses: actions/checkout@v4
        with:
          submodules: 'false'

      - name: Build oct-hdf5
        run: make -j $(nproc)

      - name: Test oct-hdf5
        run: make check

  build_and_test_ubuntu_22.04_6.4:
    name: Compile and run Tests 22.04/6.4
    
    runs-on: ubuntu-20.04
    
    container:
      image: gnuoctave/octave:6.4.0
      volumes:
        - ${{ github.workspace }}:/app

    steps:
      - name: Check Out the Repo
        uses: actions/checkout@v4
        with:
          submodules: 'false'

      - name: Build oct-hdf5
        run: make -j $(nproc)

      - name: Test oct-hdf5
        run: make check
